apiVersion: v1
kind: Service
metadata:
  name: navteqtmcdedi-service
  namespace: uat
  labels:
    app: navteqtmcdedi
    team: etl
    type: uat
    comp: di
    price: ttdi
spec:
  selector:
    app: navteqtmcdedi
  type: ClusterIP
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8080